name: Unit test cases for TCA
on: [push,pull_request]
jobs:
  run-unit-tests:
    name: Run unit test cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cleanup
        run: |
          bash clean.sh
      - name: Setup Containerization Advisor
        run: |
          bash setup.sh

      - name: Linting
      
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        id: run-unit-tests
        run: |
          python -m unittest discover -v -s test -p test_*.py
      
       
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          version: "v0.1.13"      
  