name: test-cases-git-actions
on: [push,pull_request]
jobs:
  run-unit-tests:
    name: Run unit test cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cleanup
        run: |
          bash clean.sh
      - name: Setup Containerization Advisor
        run: |
          bash setup.sh
      - name: Test with pytest
        id: run-unit-tests
        run: |
          python -m unittest discover -v -s test -p test_*.py
          echo "Unit test return value = $?"
  release-project:
    name: Release project
    needs: [run-unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          SEMVER: v0.1.0
        with:
          tag_name: ${SEMVER}
          release_name: ${SEMVER}
          body: |
            Changes in this Release
            - Initial release 
          draft: false
          prerelease: false